spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db_name
    username: viro_user
    password: viro_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

